In [385]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

# carga de conjunto de datos

In [386]:
df = pd.read_csv("https://breathecode.herokuapp.com/asset/internal-link?id=2326&path=adult-census-income.csv" , sep=",")
df.head()

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,?,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K

# Descripcion de las variables

## Age:

se refiere a la edad

## workclasss:

variable categorica que tener valores de: Privado, Autónomo no inc., Autónomo inc., Gobierno federal, Gobierno local, Gobierno estatal, Sin paga, Nunca trabajó.

## fnlwgt: 

caracteristica de numero entero, poblacion con caracteristicas similares a la persona sobre la cual se ha hecho el registro.. existe fnlwgt registros que compartes caracteristicas similares.

## Educación: 

variable categorica que puede tener los valores de: Licenciatura, Algunos estudios universitarios, 11.º grado, Posgrado de secundaria, Escuela profesional, Asociado-acdm, Asociado-vocacional, 9.º, 7.º-8.º, 12.º, Maestría, 1.º-4.º, 10.º, Doctorado, 5.º-6.º, Preescolar

# Education.num

variable numerica que corresponde con el nivel de educacion, a mayor numero mayor nivel de educacion

## marital.status

variable categorica que puede ser: Casado-civ-cónyuge, Divorciado, Nunca casado, Separado, Viudo, Casado-cónyuge ausente, Casado-AF-cónyuge

## occupation	

variable categorica que puede ser: Soporte técnico, Reparación artesanal, Otros servicios, Ventas, Ejecutivo-gerente, Profesional-especializado, Manipuladores-limpiadores, Inspección de máquinas, Administrativo-administrativo, Agricultura-pesca, Transporte-mudanzas, Servicio doméstico privado, Servicio de protección, Fuerzas Armadas

## relationship: 

variable categorico que indica que relacion tienes con el resto de personas que viven el hogar puede ser: Esposa, Hijo propio, Esposo, No familiar, Otro familiar, Soltero.

## race

variable categorico que puede ser: Blanco, asiático-isleño del Pacífico, amerindio-esquimal, otro, negro.

## sex

variable categorica que  puede ser femenino y masculino

## capital.gain

ganancias obtenidas por inversiones o ventas de activos

## capital.loss

perdidas de capital obtenidas por inversiones o ventas de activos

## hours.per.week

variable numerica que se refiere al nummero de horas trabajadas por semana

## native.country

variable categorica que  indica de donde proviene la persona registrada, puede ser: Estados Unidos, Camboya, Inglaterra, Puerto Rico, Canadá, Alemania, Estados Unidos periféricos (Guam-USVI-etc), India, Japón, Grecia, Sur, China, Cuba, Irán, Honduras, Filipinas, Italia, Polonia, Jamaica, Vietnam, México, Portugal, Irlanda, Francia, República Dominicana, Laos, Ecuador, Taiwán, Haití, Colombia, Hungría, Guatemala, Nicaragua, Escocia, Tailandia, Yugoslavia, El Salvador, Trinadad y Tobago, Perú, Hong, Holanda-Países Bajos.

## income

variable binaria que indica el  ingreso anual siendo mayor que 50.000, o menor igual que 50.000

In [387]:
# Obtener las dimensiones
df.shape

(32561, 15)

In [388]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education.num   32561 non-null  int64
 5   marital.status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital.gain    32561 non-null  int64
 11  capital.loss    32561 non-null  int64
 12  hours.per.week  32561 non-null  int64
 13  native.country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [389]:
df.duplicated().sum

<bound method Series.sum of 0        False
1        False
2        False
3        False
4        False
         ...
32556    False
32557    False
32558    False
32559    False
32560    False
Length: 32561, dtype: bool>

In [390]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
age,32561.0,38.581647,13.640433,17.0,28.0,37.0,48.0,90.0
fnlwgt,32561.0,189778.366512,105549.977697,12285.0,117827.0,178356.0,237051.0,1484705.0
education.num,32561.0,10.080679,2.572720,1.0,9.0,10.0,12.0,16.0
capital.gain,32561.0,1077.648844,7385.292085,0.0,0.0,0.0,0.0,99999.0
capital.loss,32561.0,87.303830,402.960219,0.0,0.0,0.0,0.0,4356.0
hours.per.week,32561.0,40.437456,12.347429,1.0,40.0,40.0,45.0,99.0

## Observaciones

tenemos que los registros estan comprendidos de personas entre los 17 y 90 años,

tenemos 16 niveles de educación en donde un número mas alto corresponde a un mayor nivel de edución,

tenemos los niveles de perdida y ganancia de capital en donde mas del 75% tienen valores de 0,

un minimo de horas registradas por semana de 1 hora y un maximo de 99, siendo la media de 40 horas por semana

# Limpieza de datos

In [391]:
#datos duplicados
df.duplicated().sum()

np.int64(24)

In [392]:
# eliminar los datos duplicados
df.drop_duplicates(inplace=True)

## limpiezas de columnas y filas

Definimos que las variables que el algoritmo no utilizará en el son:

capital.gain, capita.loss, marital.status, relationship, education

In [393]:
df = df.drop(columns=["fnlwgt", "capital.gain", "capital.loss", "marital.status", "relationship", "education"])
df.head(5)

,age,workclass,education.num,occupation,race,sex,hours.per.week,native.country,income
0,90,?,9,?,White,Female,40,United-States,<=50K
1,82,Private,9,Exec-managerial,White,Female,18,United-States,<=50K
2,66,?,10,?,Black,Female,40,United-States,<=50K
3,54,Private,4,Machine-op-inspct,White,Female,40,United-States,<=50K
4,41,Private,10,Prof-specialty,White,Female,40,United-States,<=50K

## modificacion de valores

In [394]:
# reemplazo de valores "?" por valores nulos
df.replace("?", pd.NA, inplace=True)

#eliminar filas con valores nulos
df.dropna(inplace=True)

df.shape

(30139, 9)

al eliminar las filas que no contenian valores podemos observar que ahora tenemos 30.139 filas, se han eliminado 2398 filas con valores nulos.

In [395]:
# transformar nuestra variable de ingreso a 0 y  1

df['income'] = df['income'].str.strip()
df['income'] = df['income'].apply(lambda x: 1 if x == '>50K' else 0)

In [396]:
# realizando one-hot-encoding para pasar a numerico las variables de clasificacion
categorical_cols = ["workclass","occupation", "sex", "race", "native.country"]
df_encoded = pd.get_dummies(df, columns=categorical_cols, dtype=int)

In [397]:
# Normalizacion de las variables numericas

scaler = StandardScaler()

df_encoded[['age', 'hours.per.week','education.num']] = scaler.fit_transform(
    df_encoded[['age', 'hours.per.week', 'education.num']]
)

In [398]:
df_encoded.head(5)

,age,education.num,hours.per.week,income,workclass_Federal-gov,workclass_Local-gov,workclass_Private,workclass_Self-emp-inc,workclass_Self-emp-not-inc,workclass_State-gov,...,native.country_Portugal,native.country_Puerto-Rico,native.country_Scotland,native.country_South,native.country_Taiwan,native.country_Thailand,native.country_Trinadad&Tobago,native.country_United-States,native.country_Vietnam,native.country_Yugoslavia
1,3.317157,-0.440434,-1.914647,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,1.184832,-2.402221,-0.078031,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
4,0.194824,-0.048076,-0.078031,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
5,-0.338257,-0.440434,0.339381,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
6,-0.033639,-1.617506,-0.078031,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0

# 3. Define el problema de recomendación:

## ¿Qué se quiere recomendar?
Trayectorias socio-laborales que aumenten la probabilidad de ganar >50K, por ejemplo:

cambiar de Ocupacion

mejorar el nivel educativo

aumentar las horas de trabajo por semana

## ¿Cuál será el "usuario" en este caso?

cada persona en el dataset es un usuario

## ¿Qué variables definen el perfil de un usuario?

la Edad, nivel de educación, Ocupación, clase de trabajo, Horas trabajadas por semana, Sexo, Raza, País de procedencia.

# 4. Construye el sistema de recomendación. 


El filtrado basado en contenido, recomienda basándose en las características del propio usuario
y de otros usuarios similares según esas características y compara que caracteristicas tienen esos usuarios que son similares pero que ganan mas de 50k al año para recomendar al usuario objetivo a cambiar algunas de sus caracteristicas

## Definicion del usuario

dejamos la fila completa eliminando la variable objetivo

In [399]:
X = df_encoded.drop(columns=['income'])
y = df_encoded['income']

In [400]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [401]:
# usuario aleatorio de prueba con ingreso <=50K
usuario_idx = y[y == 0].sample(1).index[0]

In [402]:
# ver el perfil del usuario seleccionado
print("Perfil del usuario seleccionado:")
display(df.loc[[usuario_idx]])

Perfil del usuario seleccionado:

,age,workclass,education.num,occupation,race,sex,hours.per.week,native.country,income
20586,55,Self-emp-not-inc,6,Transport-moving,White,Male,50,United-States,0

In [403]:
usuario_vector = X.loc[[usuario_idx]]

In [404]:
proba = model.predict_proba(usuario_vector)[0][1]

print(f"Probabilidad de ganar >50K: {proba:.2f}")

Probabilidad de ganar >50K: 0.17

In [405]:
# calcular similitudes entre usuarios

similarity_matrix = cosine_similarity(X)

In [406]:
similarities = similarity_matrix[usuario_idx]
idx_sorted = similarities.argsort()[::-1]

similares_pos = [
    i for i in idx_sorted
    if y.iloc[i] == 1
][:10]

similares_df = df.iloc[similares_pos]

In [407]:
# mostrar los usuarios similares con ingreso >50K
similares_df

,age,workclass,education.num,occupation,race,sex,hours.per.week,native.country,income
14079,29,Federal-gov,9,Tech-support,White,Male,40,United-States,1
19985,29,Federal-gov,10,Tech-support,White,Male,40,United-States,1
14008,27,Federal-gov,10,Tech-support,White,Male,40,United-States,1
18869,41,Federal-gov,9,Tech-support,White,Male,40,United-States,1
26542,40,Federal-gov,10,Tech-support,White,Male,40,United-States,1
20463,33,Federal-gov,11,Tech-support,White,Male,40,United-States,1
16391,29,Federal-gov,11,Tech-support,White,Male,42,United-States,1
23645,42,Federal-gov,9,Tech-support,White,Male,30,United-States,1
964,46,Federal-gov,11,Tech-support,White,Male,40,United-States,1
10642,49,Federal-gov,10,Tech-support,White,Male,40,United-States,1

In [408]:
generar_recomendaciones(df.loc[usuario_idx], similares_df)

['Incrementar el nivel educativo',
 'Evaluar un cambio hacia ocupaciones como: Tech-support']

In [409]:
print("\nRecomendaciones:")
for r in recomendaciones:
    print("-", r)

Recomendaciones:
- Aumentar horas trabajadas por semana

# ingreso manual

anteriormente se utilizo un usuario del mismo dataframe, se procedera a ingresar manualmente los datos de un nuevo usuario y asi tambien nos servira para visualizar nuestro modelo en streamlit

In [410]:
# nuevo usuario de prueba
nuevo_usuario = {
    'age': 42,
    'workclass': 'Private',
    'education.num': 10,
    'occupation': 'Sales',
    'sex': 'Female',
    'race': 'White',
    'native.country': 'United-States',
    'hours.per.week': 40
}

user_df = pd.DataFrame([nuevo_usuario])

In [411]:
# ONE-HOT ENCODING alineado con el dataset entrenado

user_encoded = pd.get_dummies(user_df)

user_encoded = user_encoded.reindex(
    columns=X.columns,
    fill_value=0
)

In [412]:
#Escalar solo variables numéricas

user_encoded[['age', 'hours.per.week', 'education.num']] = scaler.transform(
    user_encoded[['age', 'hours.per.week', 'education.num']]
)

In [413]:
# predecir la probabilidad de que el nuevo usuario gane >50K

proba = model.predict_proba(user_encoded)[0][1]
print(f"Probabilidad de ganar >50K: {proba:.2f}")

Probabilidad de ganar >50K: 0.12

# RECOMENDACIÓN POR SIMILITUD

Ahora comparamos al usuario nuevo con los existentes.

In [414]:
# concatenar el usuario nuevo al dataset original

X_extended = pd.concat([X, user_encoded], ignore_index=True)

In [415]:
# Re-calcular similitudes con el nuevo usuario
similarity_matrix = cosine_similarity(X_extended)

In [416]:
user_pos = X_extended.shape[0] - 1
similarities = similarity_matrix[user_pos]
idx_sorted = similarities.argsort()[::-1]

In [417]:
# Filtrar usuarios con ingreso >50K

similares_pos = [
    i for i in idx_sorted
    if i < len(y) and y.iloc[i] == 1
][:10]

similares_df = df.iloc[similares_pos]

In [418]:
# mostrar los usuarios similares con ingreso >50K

similares_df

,age,workclass,education.num,occupation,race,sex,hours.per.week,native.country,income
10614,40,Private,10,Sales,White,Female,40,United-States,1
22660,38,Private,10,Sales,White,Female,40,United-States,1
2776,37,Private,10,Sales,White,Female,40,United-States,1
31850,37,Private,10,Sales,White,Female,40,United-States,1
30603,42,Private,9,Sales,White,Female,40,United-States,1
7556,44,Private,9,Sales,White,Female,40,United-States,1
28651,40,Private,9,Sales,White,Female,40,United-States,1
25933,39,Private,10,Sales,White,Female,45,United-States,1
7570,46,Private,9,Sales,White,Female,40,United-States,1
10133,49,Private,10,Sales,White,Female,40,United-States,1

In [419]:
generar_recomendaciones(nuevo_usuario, similares_df)

['Aumentar las horas trabajadas por semana']

# Funciones

In [420]:
def generar_recomendaciones(nuevo_usuario, similares_df):
    """
    Genera recomendaciones basadas en la comparación del usuario
    con perfiles similares que tienen ingresos altos.
    """

    recomendaciones = []

    # Educación
    if similares_df['education.num'].min() > nuevo_usuario['education.num']:
        recomendaciones.append("Incrementar el nivel educativo")

    # Horas trabajadas
    if similares_df['hours.per.week'].mean() > nuevo_usuario['hours.per.week']:
        recomendaciones.append("Aumentar las horas trabajadas por semana")

    # Ocupación
    top_occupations = similares_df['occupation'].value_counts().head(3).index
    if nuevo_usuario['occupation'] not in top_occupations:
        recomendaciones.append(
            f"Evaluar un cambio hacia ocupaciones como: {', '.join(top_occupations)}"
        )

    return recomendaciones